### PR TITLE
code formatting and folder structure

### PR DESCRIPTION
**Pull request by daimor**
Just fixed folder structure, from simple cls, to src and complete class package path
Fixed code formatting

### CODE REVIEW

**Comment by isc-solon** [comment]
Two questions:
1. How/why did the first letter of all commands become Capitalized? 
2. Do you know why some of the quoted text is highlighted in red?

**Comment by daimor** [comment]
1. It's formatting feature added with the latest release with Option+Shift+F shortcut. It has three options: upper, lower and word which is by default, which capitalize first one or two letters. "objectscript.format.commands", "objectscript.format.functions"
2. Could you add, screenshot, I'm not sure what you mean?

**Comment by isc-solon** [comment]
1. OK. Would you please change it to "objectscript.format": {
     "commandCase": "lower",
     "functionCase": "lower"
   },
...so that it matches the format in the ObjectScript tutorial?

2. See the red highlighting here? But notice that "Last, First" near the bottom is **not** red.
Screen Shot 2019-10-01 at 12 27 47 PM

**Comment by daimor** [comment]
1. Ok, I'll do it. But for the future we would need one style.
2. Don't care about it, GitHub highlighting a bit wrong, I'll fix it later.

**Comment by daimor** [comment]
well, formatting returned back to lower

**Pull request merged**
